server:
  port: 8080

spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-source-enabled: true
          property-sources[0]:
            endpoint: https://xxxx.vault.azure.net/
            tenant-id: xxxx.onmicrosoft.com
            client-id: xxxx
            client-secret: xxxx

test: ${someProperty}